name: Build kernel
on:
  workflow_dispatch:

jobs:
  build-kernel-a12:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android12-5.10
      version_name: android12-5.10.185
      tag: android12-5.10-2023-09
      os_patch_level: 2023-09
