name: Build LKM
on:
  workflow_dispatch:

jobs:
  build-lkm:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android14-6.1
      version_name: android14-6.1.84
      tag: android14-6.1-2024-07
      os_patch_level: 2024-07
      module_dir: exianb
      module_name: exianb
      module_config: PVM_MOD
      build_lkm: true
