name: Build Multiple LKM exianb
on:
  workflow_dispatch:

jobs:
  build-pvm:
    strategy:
      matrix:
        include:
          - version: android12-5.10
            sub_level: 185
            os_patch_level: 2023-09
          - version: android13-5.15
            sub_level: 137
            os_patch_level: 2023-12
          - version: android14-6.1
            sub_level: 84
            os_patch_level: 2024-07
          - version: android15-6.6
            sub_level: 30
            os_patch_level: 2024-08
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      module_dir: exianb
      module_name: exianb
      module_config: PVM_MOD
      build_lkm: true
