name: Build Kernel Module

on:
  workflow_dispatch:
    inputs:
      module_dir:
        description: 'Module directory to build'
        required: true
        type: choice
        options:
        - exianb-dev
        - exianb
        - ovo
        - prctl-fd
        - prctl-hook
        - offset
        - hello-world
        default: 'exianb-dev'
      build_mode:
        description: 'Build mode'
        required: true
        type: choice
        options:
        - ddk
        - legacy
        default: 'ddk'

jobs:
  ddk-build:
    if: inputs.build_mode == 'ddk'
    name: Build ${{ inputs.module_dir }}.ko for ${{ matrix.kmi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
         # - android16-6.12

    container:
      image: ghcr.io/ylarod/ddk:${{ matrix.kmi }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build ${{ inputs.module_dir }}.ko
      run: |
        echo "=== Building ${{ inputs.module_dir }}.ko for KMI: ${{ matrix.kmi }} ==="

        # Build the module
        make -C $KERNEL_SRC M=$PWD/${{ inputs.module_dir }} modules
        
        echo "=== Build completed ==="

        # Create output directory
        mkdir -p /github/workspace/out
        
        # Copy with KMI-specific naming
        OUTPUT_NAME="${{ inputs.module_dir }}-${{ matrix.kmi }}.ko"
        if [ -f "${{ inputs.module_dir }}/${{ inputs.module_dir }}.ko" ]; then
            cp "${{ inputs.module_dir }}/${{ inputs.module_dir }}.ko" "/github/workspace/out/$OUTPUT_NAME"
            echo "Copied to: /github/workspace/out/$OUTPUT_NAME"
            ls -la "/github/workspace/out/$OUTPUT_NAME"
            echo "Size: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"
            llvm-strip -d "/github/workspace/out/$OUTPUT_NAME"
            echo "Size after stripping: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"
        else
            echo "ERROR: Module file not found in ${{ inputs.module_dir }}/!"
            echo "Looking for: ${{ inputs.module_dir }}/${{ inputs.module_dir }}.ko"
            echo "Files in directory:"
            ls -la "${{ inputs.module_dir }}/"
            echo "=== Checking for any .ko files ==="
            find "${{ inputs.module_dir }}/" -name "*.ko" -ls
            exit 1
        fi

    - name: Upload ${{ inputs.module_dir }}.ko artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.module_dir }}-${{ matrix.kmi }}
        path: /github/workspace/out/${{ inputs.module_dir }}-${{ matrix.kmi }}.ko

  legacy-build:
    if: inputs.build_mode == 'legacy'
    name: Build ${{ inputs.module_dir }}.ko for ${{ matrix.version }}
    strategy:
      matrix:
        include:
          - version: android12-5.10
            sub_level: 185
            os_patch_level: 2023-09
          - version: android13-5.15
            sub_level: 137
            os_patch_level: 2023-12
          - version: android14-6.1
            sub_level: 84
            os_patch_level: 2024-07
          - version: android15-6.6
            sub_level: 30
            os_patch_level: 2024-08
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      module_dir: ${{ inputs.module_dir }}
      module_name: ${{ inputs.module_dir }}
      module_config: PVM_MOD
      build_lkm: true
