name: Build Kernel Module ddk

on:
  workflow_dispatch:
    inputs:
      module_dir:
        description: 'Module directory to build'
        required: true
        type: choice
        options:
        - exianb-dev
        - exianb
        - ovo
        - prctl-fd
        - prctl-hook
        - offset
        - hello-world
        - wuwa
        default: 'exianb-dev'

jobs:
  ddk-build:
    name: Build ${{ inputs.module_dir }}.ko for ${{ matrix.kmi }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
         # - android16-6.12

    container:
      image: ghcr.io/ylarod/ddk:${{ matrix.kmi }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build ${{ inputs.module_dir }}.ko
      run: |
        echo "=== Building ${{ inputs.module_dir }}.ko for KMI: ${{ matrix.kmi }} ==="

        # Build the module
        make -C $KERNEL_SRC M=$PWD/${{ inputs.module_dir }} modules
        
        echo "=== Build completed ==="

        # Create output directory
        mkdir -p /github/workspace/out
        
        # Find the first .ko file in the module directory
        KO_FILE=$(find "${{ inputs.module_dir }}" -name "*.ko" -type f | head -1)
        
        TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
        OUTPUT_NAME="${{ inputs.module_dir }}-${{ matrix.kmi }}-$TIMESTAMP.ko"
        if [ -n "$KO_FILE" ] && [ -f "$KO_FILE" ]; then
            cp "$KO_FILE" "/github/workspace/out/$OUTPUT_NAME"
            echo "Copied: $KO_FILE -> /github/workspace/out/$OUTPUT_NAME"
            echo "Size: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"
            llvm-strip -d "/github/workspace/out/$OUTPUT_NAME"
            echo "Size after stripping: $(du -h "/github/workspace/out/$OUTPUT_NAME" | cut -f1)"
        else
            echo "ERROR: No .ko file found in ${{ inputs.module_dir }}/!"
            echo "Available files in ${{ inputs.module_dir }}/:"
            ls -la "${{ inputs.module_dir }}/" || echo "Directory doesn't exist"
            exit 1
        fi

    - name: Upload ${{ inputs.module_dir }}.ko artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.module_dir }}-${{ matrix.kmi }}-${{ github.run_id }}
        path: /github/workspace/out/${{ inputs.module_dir }}-${{ matrix.kmi }}-*.ko
