name: GKI Kernel Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      os_patch_level:
        required: false
        type: string
        default: "2022-05"
      module_dir:
        required: false
        type: string
        default: "kernelsu"
      module_name:
        required: false
        type: string
        default: ""
      module_config:
        required: false
        type: string
        default: "PVM_MOD"
      use_cache:
        required: false
        type: boolean
        default: true
      build_lkm:
        required: false
        type: boolean
        default: false
      build_in_tree:
        required: false
        type: boolean
        default: true   # inbuilt image builds

jobs:
  build:
    name: Build ${{ inputs.version_name }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Checkout module repo
        uses: actions/checkout@v4
        with:
          path: KernelSU
          fetch-depth: 0

      - name: Setup kernel source (repo sync)
        run: |
          set -euo pipefail
          sudo apt-get update -y
          sudo apt-get install -y repo
          mkdir -p android-kernel && cd android-kernel
          repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-${{ inputs.tag }} --repo-rev=v2.16
          REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${{ inputs.tag }})
          if grep -q deprecated <<< "$REMOTE_BRANCH"; then
            sed -i 's/"${{ inputs.tag }}"/"deprecated\/${{ inputs.tag }}"/g' .repo/manifests/default.xml
          fi
          repo sync -c -j"$(nproc --all)" --no-tags

      - name: Remove dirty marks (ADDED CLEANING)
        working-directory: android-kernel
        run: |
          set -euo pipefail
          
          # Set controlled timestamp
          CURRENT_TIME=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
          echo "CURRENT_TIME=$CURRENT_TIME"
          
          # 1. Fix UTS_VERSION in mkcompile_h
          perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_TIME\"}" ./common/scripts/mkcompile_h

          # 2. Remove -dirty from setlocalversion
          sed -i 's/-dirty//' ./common/scripts/setlocalversion

          # 3. Fix Makefile timestamp for 6.1/6.6 kernels
          KERNEL_VERSION=$(echo "${{ inputs.tag }}" | grep -oE '[0-9]+\.[0-9]+' | head -1)
          if [ "$KERNEL_VERSION" = "6.1" ] || [ "$KERNEL_VERSION" = "6.6" ]; then
            sed -i -e "s|\$(preempt-flag-y) \"\$(build-timestamp)\"|\$(preempt-flag-y) \"$CURRENT_TIME\"|" ./common/init/Makefile
          fi
          
          # 4. Bazel-specific cleanups
          if [ ! -f "build/build.sh" ]; then
            sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
            rm -rf ./common/android/abi_gki_protected_exports_*
            sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          fi

          # 5. Set custom version if provided
          if [ ! -z "${{ inputs.version }}" ]; then
            sed -i '$s|echo "$res"|echo "${{ inputs.version }}"|' ./common/scripts/setlocalversion
          fi

      - name: Setup Module (embed into kernel tree)
        run: |
          set -euo pipefail
          MODULE_DIR="${{ inputs.module_dir }}"
          MODULE_NAME="${{ inputs.module_name }}"
          MODULE_CONFIG="${{ inputs.module_config }}"
          if [ -z "$MODULE_NAME" ]; then MODULE_NAME="$MODULE_DIR"; fi

          cd android-kernel
          TARGET_DIR="common/drivers/${MODULE_DIR}"
          ln -sfn "$GITHUB_WORKSPACE/KernelSU/$MODULE_DIR" "$TARGET_DIR"

          DRIVER_KCONFIG="common/drivers/Kconfig"
          if ! grep -q "drivers/${MODULE_DIR}/Kconfig" "$DRIVER_KCONFIG"; then
            sed -i "/endmenu/i\\source \"drivers/${MODULE_DIR}/Kconfig\"" "$DRIVER_KCONFIG"
          fi

          DRIVER_MAKEFILE="common/drivers/Makefile"
          if ! grep -q "${MODULE_DIR}/" "$DRIVER_MAKEFILE"; then
            echo "obj-\$(CONFIG_${MODULE_CONFIG}) += ${MODULE_DIR}/" >> "$DRIVER_MAKEFILE"
          fi

          echo "[+] Wired ${MODULE_DIR} into drivers/Makefile and drivers/Kconfig."

      - name: Setup ccache
        if: ${{ inputs.use_cache == true }}
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: gki-kernel-aarch64-${{ inputs.version_name }}
          max-size: 2G

      - name: Build Kernel (Image)
        working-directory: android-kernel
        run: |
          set -euo pipefail
          if [ -e build/build.sh ]; then
            # build.sh path
            LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 \
            build/build.sh CC="/usr/bin/ccache clang"
          else
            # Bazel (kleaf) path
            tools/bazel run --disk_cache=$HOME/.cache/bazel --config=fast --config=stamp --lto=thin \
              //common:kernel_aarch64_dist -- --dist_dir=dist
          fi

      - name: Prepare artifacts
        run: |
          set -euo pipefail
          OUTDIR="android-kernel/out/${{ inputs.version }}/dist"
          [ -d "$OUTDIR" ] || OUTDIR="android-kernel/dist"
          mkdir -p output

          # Copy all kernel images
          cp "$OUTDIR"/Image* output/ 2>/dev/null || true

          # Prepare AnyKernel3 with only one image format
          git clone https://github.com/Kernel-SU/AnyKernel3 anykernel3
          rm -rf anykernel3/.git
          
          # Copy only the uncompressed Image to AnyKernel3
          cp output/Image anykernel3/ 2>/dev/null || true
          
          # Create AnyKernel3 zip with only Image (not gz/lz4)
          cd anykernel3
          zip -r AnyKernel3.zip . -x "*.git*" "README.md" "LICENSE"
          cd ..
          mv anykernel3/AnyKernel3.zip output/
          rm -rf anykernel3

          # Prepare individual compressed images for separate artifacts
          mkdir -p output/individual
          if [ -f "output/Image" ]; then
            cp output/Image "output/individual/${{ inputs.version_name }}_${{ inputs.os_patch_level }}"
          fi
          if [ -f "output/Image.gz" ]; then
            cp output/Image.gz "output/individual/${{ inputs.version_name }}_${{ inputs.os_patch_level }}.gz"
          fi
          if [ -f "output/Image.lz4" ]; then
            cp output/Image.lz4 "output/individual/${{ inputs.version_name }}_${{ inputs.os_patch_level }}.lz4"
          fi

      - name: Upload AnyKernel3 Zip (Single Format)
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-${{ inputs.version_name }}_${{ inputs.os_patch_level }}
          path: output/AnyKernel3.zip

      - name: Upload Individual Compressed Images
        uses: actions/upload-artifact@v4
        with:
          name: kernel-images-${{ inputs.version_name }}_${{ inputs.os_patch_level }}
          path: output/individual/*
