name: GKI Kernel Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      version_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      os_patch_level:
        required: false
        type: string
        default: "2022-05"
      module_dir:
        required: false
        type: string
        default: "kernelsu"
      module_name:
        required: false
        type: string
        default: ""
      module_config:
        required: false
        type: string
        default: "PVM_MOD"
      use_cache:
        required: false
        type: boolean
        default: true
      build_lkm:
        required: false
        type: boolean
        default: false
      build_in_tree:
        required: false
        type: boolean
        default: true

jobs:
  build:
    name: Build ${{ inputs.version_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Clean workspace
        run: |
          sudo rm -rf android-kernel output bootimgs AnyKernel3 $CONFIG
          mkdir -p output bootimgs

      - name: Checkout module repo
        uses: actions/checkout@v4
        with:
          path: KernelSU
          fetch-depth: 0

      - name: Set CONFIG environment variable
        run: |
          CONFIG="${{ inputs.version_name }}"
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git curl repo

      - name: Clone AnyKernel3
        run: |
          git clone https://github.com/Kernel-SU/AnyKernel3.git
          rm -rf AnyKernel3/.git

      - name: Initialize and sync kernel source
        run: |
          mkdir -p "$CONFIG"
          cd "$CONFIG"
          repo init --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-${{ inputs.tag }} --repo-rev=v2.16
          REMOTE_BRANCH=$(git ls-remote https://android.googlesource.com/kernel/common ${{ inputs.tag }})
          if grep -q deprecated <<< "$REMOTE_BRANCH"; then
            sed -i "s/\"${{ inputs.tag }}\"/\"deprecated\/${{ inputs.tag }}\"/g" .repo/manifests/default.xml
          fi
          repo sync -c -j$(nproc --all) --no-tags --fail-fast

      - name: Clean kernel build directories
        run: |
          cd "$CONFIG"
          rm -rf out build-out dist
          make -C common clean 2>/dev/null || true
          make -C common mrproper 2>/dev/null || true

      - name: Disable defconfig check (FIX FOR CONFIG ERROR)
        run: |
          cd "$CONFIG"
          # Remove the defconfig validation that causes the error
          if [ -f "build/build.sh" ]; then
            sed -i 's/check_defconfig//' ./common/build.config.gki.aarch64
            sed -i 's/check_defconfig//' ./common/build.config.gki
          fi

      - name: Setup Module (embed into kernel tree)
        run: |
          cd "$CONFIG"
          MODULE_DIR="${{ inputs.module_dir }}"
          MODULE_CONFIG="${{ inputs.module_config }}"
          
          # Clean existing module directory
          rm -rf "common/drivers/${MODULE_DIR}"
          
          # Create symlink to your module
          ln -sfn "$GITHUB_WORKSPACE/KernelSU/$MODULE_DIR" "common/drivers/${MODULE_DIR}"
          
          # Clean and add to Kconfig
          sed -i "/source \"drivers\/${MODULE_DIR}\/Kconfig\"/d" "common/drivers/Kconfig"
          sed -i "/endmenu/i\\source \"drivers/${MODULE_DIR}/Kconfig\"" "common/drivers/Kconfig"
          
          # Clean and add to Makefile
          sed -i "/${MODULE_DIR}\//d" "common/drivers/Makefile"
          echo "obj-\$(CONFIG_${MODULE_CONFIG}) += ${MODULE_DIR}/" >> "common/drivers/Makefile"
          
          echo "✅ Successfully embedded $MODULE_DIR into kernel tree"

      - name: Enable module in kernel config (PROPER METHOD)
        run: |
          cd "$CONFIG"
          CONFIG_FILE="common/arch/arm64/configs/gki_defconfig"
          
          # Remove any existing config to avoid duplicates
          sed -i "/CONFIG_${MODULE_CONFIG}=/d" "$CONFIG_FILE"
          
          # Add the config at the end of the file (safest location)
          echo "# ${{ inputs.module_name }} module" >> "$CONFIG_FILE"
          echo "CONFIG_${MODULE_CONFIG}=y" >> "$CONFIG_FILE"
          
          echo "✅ Added CONFIG_${MODULE_CONFIG}=y to kernel config"

      - name: Configure kernel name and version
        run: |
          cd "$CONFIG"
          
          # Custom version editing
          if [ ! -z "${{ inputs.version }}" ]; then
            echo "Version is not empty: ${{ inputs.version }}"
            sed -i '$s|echo "$res"|echo "${{ inputs.version }}"|' ./common/scripts/setlocalversion
          else
            echo "Version is empty, using default"
            sed -i '$s|echo "$res"|echo "$res-custom-build"|' ./common/scripts/setlocalversion
          fi

          # Set controlled timestamp
          CURRENT_TIME=$(date -u +"%a %b %d %H:%M:%S UTC %Y")
          echo "CURRENT_TIME=$CURRENT_TIME"
          
          # Fix UTS_VERSION in mkcompile_h
          perl -pi -e "s{UTS_VERSION=\"\\\$\(echo \\\$UTS_VERSION \\\$CONFIG_FLAGS \\\$TIMESTAMP \\| cut -b -\\\$UTS_LEN\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $CURRENT_TIME\"}" ./common/scripts/mkcompile_h

          # Remove -dirty from setlocalversion
          sed -i 's/-dirty//' ./common/scripts/setlocalversion

          # Fix Makefile timestamp for 6.1/6.6 kernels
          KERNEL_VERSION=$(echo "${{ inputs.tag }}" | grep -oE '[0-9]+\.[0-9]+' | head -1)
          if [ "$KERNEL_VERSION" = "6.1" ] || [ "$KERNEL_VERSION" = "6.6" ]; then
            sed -i -e "s|\$(preempt-flag-y) \"\$(build-timestamp)\"|\$(preempt-flag-y) \"$CURRENT_TIME\"|" ./common/init/Makefile
          fi
          
          # Bazel-specific cleanups
          if [ ! -f "build/build.sh" ]; then
            sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' ./common/BUILD.bazel
            rm -rf ./common/android/abi_gki_protected_exports_*
            sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
            
            # Also set version in gki_defconfig for Bazel builds
            if [ ! -z "${{ inputs.version }}" ]; then
              sed -i '/^CONFIG_LOCALVERSION=/ s/="\([^"]*\)"/="${{ inputs.version }}"/' ./common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: Apply build config modifications
        run: |
          cd "$CONFIG"
          # Apply build config cleanups to prevent various issues
          sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' common/build.config.gki.aarch64
          sed -i '/MODULES_ORDER=android\/gki_aarch64_modules/d' common/build.config.gki.aarch64
          sed -i '/KMI_SYMBOL_LIST_STRICT_MODE/d' common/build.config.gki.aarch64
          
          echo "✅ Applied build config modifications"

      - name: Build kernel
        run: |
          cd "$CONFIG"
          
          if [ -f "build/build.sh" ]; then
            echo "Building with build.sh..."
            LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
          else
            echo "Building with Bazel..."
            tools/bazel build --config=fast --lto=thin //common:kernel_aarch64_dist
          fi
          
          echo "✅ Kernel build completed successfully"

      - name: Prepare artifacts
        run: |
          # Find output directory
          if [ -d "$CONFIG/out/${{ inputs.version }}/dist" ]; then
            OUTDIR="$CONFIG/out/${{ inputs.version }}/dist"
          elif [ -d "$CONFIG/dist" ]; then
            OUTDIR="$CONFIG/dist" 
          elif [ -d "$CONFIG/bazel-bin/common/kernel_aarch64" ]; then
            OUTDIR="$CONFIG/bazel-bin/common/kernel_aarch64"
          else
            echo "ERROR: Could not find kernel output directory"
            find "$CONFIG" -name "Image*" -type f | head -10
            exit 1
          fi

          echo "Found kernel output in: $OUTDIR"
          ls -la "$OUTDIR" || echo "Output directory listing failed"

          # Copy kernel images
          cp "$OUTDIR"/Image* ./ 2>/dev/null || true
          cp "$OUTDIR"/Image* ./AnyKernel3/ 2>/dev/null || true
          
          # List what we found
          echo "Kernel images found:"
          ls -la ./Image* 2>/dev/null || echo "No Image files in root"
          echo "AnyKernel3 contents:"
          ls -la ./AnyKernel3/ 2>/dev/null || echo "AnyKernel3 directory issue"

      - name: Create AnyKernel3 zip
        run: |
          cd AnyKernel3
          
          # Check if we have kernel images
          if [ ! -f "Image" ] && [ ! -f "Image.lz4" ] && [ ! -f "Image.gz" ]; then
            echo "❌ No kernel images found in AnyKernel3 directory!"
            ls -la
            exit 1
          fi
          
          zip -r "../output/${{ inputs.version_name }}_${{ inputs.os_patch_level }}-AnyKernel3.zip" ./*
          echo "✅ Created AnyKernel3 zip"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-${{ inputs.version_name }}_${{ inputs.os_patch_level }}
          path: |
            output/*
            AnyKernel3/Image*
