name: Build OFFSET
on:
  workflow_dispatch:

jobs:
  build-lkm:
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: android14-6.1
      version_name: android14-6.1.84
      tag: android14-6.1-2024-07
      os_patch_level: 2024-07
      module_dir: offset
      module_name: offset_printer
      module_config: OFFSET_PRINTER
      build_lkm: true
