name: Universal Kernel Module Builder

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Select build type'
        required: true
        type: choice
        options:
          - lkm
          - embedded
        default: lkm
      module_dir:
        description: 'Select module directory inside the repository'
        required: true
        type: choice
        options:
          - exianb-dev
          - exianb
          - ovo
          - ovo-main
          - prctl-fd
          - prctl-hook
          - hello-world
          - offset
        default: exianb
      module_name:
        description: 'Name of module (defaults to module_dir)'
        required: false
        type: string
        default: ''
      module_config:
        description: 'Kconfig symbol for the module (e.g. PVM_MOD)'
        required: false
        type: string
        default: PVM_MOD

jobs:
  build-lkm:
    if: github.event.inputs.build_type == 'lkm'
    name: "${{ matrix.version }}.${{ matrix.sub_level }} • ${{ github.event.inputs.module_dir }} • LKM"
    strategy:
      matrix:
        include:
          - version: android12-5.10
            sub_level: 185
            os_patch_level: 2023-09
          - version: android13-5.15
            sub_level: 137
            os_patch_level: 2023-12
          - version: android14-6.1
            sub_level: 84
            os_patch_level: 2024-07
          - version: android15-6.6
            sub_level: 30
            os_patch_level: 2024-08

    uses: ./.github/workflows/gki-kernel-lkm.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      module_dir: ${{ github.event.inputs.module_dir }}
      module_name: ${{ github.event.inputs.module_name != '' && github.event.inputs.module_name || github.event.inputs.module_dir }}
      module_config: ${{ github.event.inputs.module_config }}
      use_cache: true

  build-embedded:
    if: github.event.inputs.build_type == 'embedded'
    name: "${{ matrix.version }}.${{ matrix.sub_level }} • ${{ github.event.inputs.module_dir }} • Embedded"
    strategy:
      matrix:
        include:
         # - version: android12-5.10
         #   sub_level: 185
         #   os_patch_level: 2023-09
          - version: android13-5.15
            sub_level: 137
            os_patch_level: 2023-12
          - version: android14-6.1
            sub_level: 84
            os_patch_level: 2024-07
          - version: android15-6.6
            sub_level: 30
            os_patch_level: 2024-08

    uses: ./.github/workflows/gki-kernel-embedded.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      module_dir: ${{ github.event.inputs.module_dir }}
      module_name: ${{ github.event.inputs.module_name != '' && github.event.inputs.module_name || github.event.inputs.module_dir }}
      module_config: ${{ github.event.inputs.module_config }}
      use_cache: true
